baseURL = 'http://hobbyfarm.github.io/'
languageCode = 'en-us'
title = 'HobbyFarm'
offlineSearch = true
enableEmoji = true
[module]
proxy = 'direct'
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false
[menu]
[[menu.main]]
  name = 'Home'
  weight = 1
  pageRef = '/'
[[menu.main]]
  name = 'Github'
  weight = 99
  url = 'https://github.com/hobbyfarm/hobbyfarm'